---
detectors:
  UncommunicativeModuleName:
    accept:
      - /::[a-zA-z]*V\d$/
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    allow_calls:
      - Settings.*
directories:
  "db/migrate":
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      accept:
        - t
  "app/sidekiq":
    UtilityFunction:
      enabled: false